version: '3.5'

services:
  db:
    image: mariadb:10.3
    container_name: "nodokamome-db"  
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1274518aAbBcC
    networks: 
      - nodokamome-network

  phpmyadmin:
    image: phpmyadmin
    container_name: "nodokamome-db-phpmyadmin"  
    restart: always
    ports:
      - 12000:80
    environment:
      - PMA_ARBITRARY=1
    networks: 
      - nodokamome-network

networks:
  nodokamome-network:
    name: nodokamome_network
