version: '3.5'

services:
  db:
    image: mariadb:10.3
    container_name: "db"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks: 
      - app-network

  phpmyadmin:
    image: phpmyadmin
    container_name: db-phpmyadmin
    restart: always
    volumes: 
      - ./phpmyadmin/phpmyadmin-misc.ini:/usr/local/etc/php/conf.d/phpmyadmin-misc.ini
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=${VIRTUAL_PORT}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - PMA_HOST=db
      - PMA_ARBITRARY=1
    networks: 
      - proxy-network  # プロキシネットワーク
      - app-network    # アプリネットワーク

# プロキシネットワーク、アプリネットワークと接続
networks:
  proxy-network:
    name: proxy_network
  app-network:
    name: app_network
